In [1]:
import keras
from keras import ops
import numpy as np

2025-01-07 10:47:52.473895: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-01-07 10:47:52.568592: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-01-07 10:47:52.595082: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-01-07 10:47:52.791519: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


#### Config

In [4]:
keras.config.backend()

'tensorflow'

In [3]:
import os
os.environ['KERAS_BACKEND'] = 'torch'  # 'tensorflow', 'jax'

In [5]:
keras.version()

'3.4.1'

In [6]:
import tensorflow as tf

tf.config.list_physical_devices("GPU")

I0000 00:00:1736247081.538203      25 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1736247081.642638      25 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
I0000 00:00:1736247081.644557      25 cuda_executor.cc:1015] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355


[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [7]:
import torch

torch.cuda.is_available()

True

#### Tensors

In [9]:
a = ops.array([1, 2, 3])
a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [13]:
a.shape
a.dtype
ops.convert_to_numpy(a)
a = ops.cast(a, 'float32')
a

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [15]:
a[:2]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>

In [16]:
a + 3

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4., 5., 6.], dtype=float32)>

In [19]:
a[0] = 0.

TypeError: 'tensorflow.python.framework.ops.EagerTensor' object does not support item assignment

#### Keras Variables

In [17]:
b = keras.Variable(a)
b

<KerasVariable shape=(3,), dtype=float32, path=variable>

In [18]:
b.value

<tf.Variable 'variable:0' shape=(3,) dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [20]:
b.trainable

True

In [21]:
b[0]

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [22]:
b[0] = 0

TypeError: 'Variable' object does not support item assignment

In [23]:
b.assign([2., 3., 4.])
ops.convert_to_numpy(b)

array([2., 3., 4.], dtype=float32)

In [24]:
b.assign_add([1., 1., 1.])
ops.convert_to_numpy(b)

array([3., 4., 5.], dtype=float32)

#### Random Tensors

In [25]:
# Numpy method for creating random arrays

c = np.random.uniform(size=(2, 3)).astype(np.float32)  # np is float64 by default
c = ops.array(c)
c

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.89623386, 0.94492656, 0.6311308 ],
       [0.47476554, 0.28417054, 0.1892012 ]], dtype=float32)>

In [26]:
# Take a look at the API docs: https://keras.io/api/random/random_ops/

d = keras.random.normal((3, 4))
d

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[ 1.2789631 , -0.65381026, -0.8222155 ,  0.54488605],
       [-0.17854883, -0.6810609 ,  0.11018339,  1.085931  ],
       [-0.32748464,  1.5268054 , -0.8087275 ,  0.06013825]],
      dtype=float32)>

#### NumPy ops

In [27]:
# np ops: https://keras.io/api/ops/#numpy-ops

ops.matmul(c, d)
# Try running ops.matmul(d, c), this gives an error

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[ 0.7708488 , -0.26590544, -1.143195  ,  1.5524254 ],
       [ 0.49450877, -0.2150706 , -0.51206094,  0.5786609 ]],
      dtype=float32)>

In [28]:
# Random Tensors in Keras: check the docs!

c = keras.random.uniform((2, 5, 3))
d = keras.random.gamma((2, 3, 4), 1.0)

In [29]:
# Batched matrix multiplication. Think of this as 2 separate matrix multiplications
# that are then combined together in a single Tensor

ops.matmul(c, d)

<tf.Tensor: shape=(2, 5, 4), dtype=float32, numpy=
array([[[2.8347647 , 3.263228  , 0.9831042 , 2.3504202 ],
        [3.1213214 , 2.5079522 , 0.8070836 , 2.104896  ],
        [2.6454437 , 3.2002556 , 0.8665238 , 1.8078835 ],
        [1.8163522 , 3.926765  , 0.8219084 , 0.9436851 ],
        [2.4002123 , 4.08649   , 1.0966523 , 2.218544  ]],

       [[1.1969165 , 0.58983016, 0.76100004, 0.8826098 ],
        [1.2758739 , 0.35296863, 0.5688492 , 0.8797903 ],
        [1.0331485 , 0.2789201 , 0.4644701 , 0.7005015 ],
        [0.6066004 , 0.6156887 , 0.6490193 , 0.5331943 ],
        [1.087866  , 0.39320752, 0.60336685, 0.731472  ]]], dtype=float32)>